
# Detalle general: hace falta información sobre esta investigación, valdría la pena encontrarle un nombre divertido 

Importante: Salvo el caso de tres, las búsquedas y objetivos de las piezas no necesariamente coinciden con los objetivos de la investigación. En todo caso, las preguntas que surgen de las piezas pueden discutir con la investigación y viceversa. 

* Marcos de trabajo

# Optmización, ofuscación, restricción, ofrecimiento y estructura  
# Practicas corruptas sdf

** Tres 
** Anti

Anti es una pieza que surgió como respuesta a tecnologías vinculadas con redes sociales como Instagram o Facebook. En específico, atiende a las tecnologías que permiten el diseño de experiencias, capas y filtros en Realidad Aumentada. En un conjunto de herramientas como la que ofrece Meta Spark ( antes llamado Spark AR), la personalización de las capas que se superponen a una imagen fija o en movimiento está determinada por una interfaz que acota las posibilidades de estas tecnologías al mismo tiempo que facilita su uso.




** Three.studies

* Expresividad

# Programación fija y programación dinámica.
# Gestualidades 
# Presentaciones. Pedirle a Marianne los recursos que tenga almacenados 

** Tres
** Three
** Anti

* Extensión

# Escrituras modulares
# Otros módulos que forman parte del proyecto
# Búsquedas estéticas del 
# Reconfiguración usuario/desarrollador 

** Three
** Anti

Tecnologías vinculadas a Meta. En este aspecto, parece que el usuario cumple con la figura del prosumidor. Para los fines de esta investigación, preferimos desplazar la relación consumo-producción a la relación uso-desarrollo y como una declaratoria inicial, prefiero sustituir la palabra desarrollo por escritura. 


** Tres 

* Integración 

# Re-entrada y retroalimentación. Recordar de dónde viene el primer concepto
# Chatbots?

** Anti

Ideas que surgieron y que formaron parte de los recursos artísticos de la pieza. Lenguaje natural y remezcla de ideas. 

** Three
** Tres
